version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    tty: true
    networks:
      - node-network
    ports:
      - "8000:80"
      - "8081:81"
    depends_on:
      - service-b
      - service-c

  service-b:
    build:
      context: ./service-b
    container_name: service-b
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./service-b:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: npm run start

  service-c:
    build:
      context: ./service-c
    container_name: service-c
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./service-c:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    command: npm run start
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    tty: true
    restart: always
    networks:
      - node-network
    environment:
      POSTGRES_USER: eulutas20
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  node-network:
    driver: bridge
